import { Handjet } from "next/font/google";
import "./globals.css";

const handjet = Handjet({
  subsets: ["latin"],
  variable: "--font-handjet",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${handjet.className} antialiased min-h-screen w-screen bg-[#EFF6F7]`}
      >
        <div className="min-h-screen w-screen">{children}</div>
      </body>
    </html>
  );
}
